name: Deploy to Azure Staging Slot

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip the site
      run: zip -r site.zip .

    - name: Deploy to Azure Staging Slot
      uses: azure/webapps-deploy@v3
      with:
        app-name: Julius-StudentApp
        slot-name: staging
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: site.zip
